import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/navigation/Header";
import Footer from "@/components/navigation/Footer";
import SectionContainer from "@/components/SectionContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Frontend Scratch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SectionContainer>
          <div className="h-screen flex flex-col justify-between font-sans">
            <Header />
            {children}
            <Footer />
          </div>
        </SectionContainer>
      </body>
    </html>
  );
}
